# Site settings
title: ZMG Matematika
motto: 
email:
description: > # this means to ignore newlines until "baseurl:"
  A Zrínyi Miklós Gimnázium Matematika honlapja
baseurl: ""
url: ""
github_username:  zmg-matematika

# Build settings
markdown: kramdown
